CREATE TABLE BIBLE (
	VerseId INT NOT NULL GENERATED ALWAYS AS IDENTITY UNIQUE,
	Language VARCHAR(25) NOT NULL,
	TestamentNum INT NOT NULL,
	Testament VARCHAR(25) NOT NULL,
	BookNum INT NOT NULL,
	Book VARCHAR(25) NOT NULL,
	Chapter INT NOT NULL,
	VerseNum INT NOT NULL,
	Verse VARCHAR(1000) NOT NULL,
	PRIMARY KEY (Language, BookNum, Chapter, VerseNum)
);